version: '3'

services:

  njinx:

    build: ./njinx/
    restart: always
    container_name: njinx
    volumes:
      - ./static:/static/

    ports:
      - "80:8000"

    depends_on:
      - site

  site:

    build: .
    container_name: food-ordering-website-server
  
    restart: always
    volumes:
      - .:/app
    
    ports:
      - "8000:8000"

    depends_on:
      - db

  db:

    image: postgres
    container_name: food-ordering-website-db
    restart: always

    environment:
      - POSTGRES_DB=food-site
      - POSTGRES_PASSWORD=strong-password

    ports:
      - "3306:3306"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - food-site

  pgadmin:

    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file:
      - ./conf/pgadmin.env

    volumes:
      - pgadmin-data:/var/lib/pgadmin
    
    networks:
      - food-site

volumes:

  postgres_data:

  storage:
    name: "site-data"
  
  pgadmin-data:
    name: "pgadmin-data"


networks:
  food-site: